-- Tenant database template: one of these D1 databases is created per
-- shop (see cloud/control-plane). Ported from the original Tauri desktop
-- app's SQLite schema (installment-manager/src-tauri/migrations), with
-- two changes for the multi-tenant cloud model:
--
--   1. Every primary/foreign key is now a TEXT UUID instead of an
--      INTEGER AUTOINCREMENT. Not required for correctness anymore (each
--      tenant DB has a single writer -- the Worker -- so there's no
--      multi-device merge to worry about), but kept as a deliberate
--      security choice: sequential integer IDs exposed in a URL let
--      anyone guess "how many sales has this shop processed" or enumerate
--      other customers' records. IDs are generated by application code
--      before insert -- D1/SQLite has no built-in UUID generator.
--   2. `license_activation` is dropped entirely. Device-bound offline
--      license/trial state has no meaning once subscription status lives
--      centrally in the Control Plane (cloud/control-plane) and is
--      checked on every request instead.
--
-- Money/currency conventions carried over unchanged (ARCHITECTURE.md §5):
--   * No REAL/FLOAT columns for money. USD is stored in cents, IQD as
--     exact Dinar integers.
--   * `*_exchange_rate_micros` stores the rate scaled by 1,000,000.
--   * `credit_sale`, `payment`, and `audit_log` are append-only:
--     application code must never UPDATE or DELETE rows in these tables.

CREATE TABLE customer (
    id          TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    phone       TEXT,
    national_id TEXT NOT NULL,
    address     TEXT,
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE UNIQUE INDEX idx_customer_national_id ON customer (national_id);

CREATE TABLE product (
    id                   TEXT PRIMARY KEY,
    name                 TEXT NOT NULL,
    reference_cash_price INTEGER NOT NULL,
    currency_code        TEXT NOT NULL CHECK (currency_code IN ('IQD', 'USD')),
    is_active            INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1))
);

-- The immutable snapshot: once created, a CreditSale and its items are
-- never updated or deleted by application code. guarantor_id references
-- another row in this same `customer` table (a guarantor is just an
-- existing customer vouching for someone else's sale).
CREATE TABLE credit_sale (
    id                          TEXT PRIMARY KEY,
    customer_id                 TEXT NOT NULL REFERENCES customer (id),
    guarantor_id                TEXT REFERENCES customer (id),
    sale_date                   TEXT NOT NULL,
    agreed_months               INTEGER NOT NULL CHECK (agreed_months > 0),
    installment_period_unit     TEXT NOT NULL DEFAULT 'months'
                                     CHECK (installment_period_unit IN ('months', 'days')),
    applied_markup_value        INTEGER NOT NULL,
    total_installment_price     INTEGER NOT NULL,
    currency_code               TEXT NOT NULL CHECK (currency_code IN ('IQD', 'USD')),
    manual_exchange_rate_micros INTEGER NOT NULL,
    created_at                  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX idx_credit_sale_customer_id ON credit_sale (customer_id);

CREATE TABLE credit_sale_item (
    id                   TEXT PRIMARY KEY,
    sale_id              TEXT NOT NULL REFERENCES credit_sale (id),
    product_id           TEXT NOT NULL REFERENCES product (id),
    snapshot_cash_price  INTEGER NOT NULL,
    quantity             INTEGER NOT NULL CHECK (quantity > 0)
);
CREATE INDEX idx_credit_sale_item_sale_id ON credit_sale_item (sale_id);
CREATE INDEX idx_credit_sale_item_product_id ON credit_sale_item (product_id);

CREATE TABLE installment (
    id                TEXT PRIMARY KEY,
    sale_id           TEXT NOT NULL REFERENCES credit_sale (id),
    due_date          TEXT NOT NULL,
    scheduled_amount  INTEGER NOT NULL CHECK (scheduled_amount > 0),
    status            TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Partial', 'Paid'))
);
CREATE INDEX idx_installment_sale_id ON installment (sale_id);
CREATE INDEX idx_installment_due_date ON installment (due_date);

-- The ledger: append-only, never updated or deleted by application code.
CREATE TABLE payment (
    id                           TEXT PRIMARY KEY,
    customer_id                  TEXT NOT NULL REFERENCES customer (id),
    payment_date                 TEXT NOT NULL,
    amount_paid                  INTEGER NOT NULL CHECK (amount_paid > 0),
    currency_code                TEXT NOT NULL CHECK (currency_code IN ('IQD', 'USD')),
    manual_exchange_rate_micros  INTEGER NOT NULL,
    created_at                   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX idx_payment_customer_id ON payment (customer_id);

CREATE TABLE payment_allocation (
    id                TEXT PRIMARY KEY,
    payment_id        TEXT NOT NULL REFERENCES payment (id),
    installment_id    TEXT NOT NULL REFERENCES installment (id),
    allocated_amount  INTEGER NOT NULL CHECK (allocated_amount > 0)
);
CREATE INDEX idx_payment_allocation_payment_id ON payment_allocation (payment_id);
CREATE INDEX idx_payment_allocation_installment_id ON payment_allocation (installment_id);

-- The trace: append-only, never updated or deleted by application code.
CREATE TABLE audit_log (
    id           TEXT PRIMARY KEY,
    table_name   TEXT NOT NULL,
    record_id    TEXT NOT NULL,
    action       TEXT NOT NULL CHECK (action IN ('INSERT', 'UPDATE', 'DELETE')),
    timestamp    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    old_payload  TEXT,
    new_payload  TEXT
);
CREATE INDEX idx_audit_log_table_record ON audit_log (table_name, record_id);

-- Customer document photos ("مستمسكات"). Unlike the original desktop
-- schema, the file itself is NOT stored here: D1 rows are not meant for
-- multi-megabyte BLOBs. `r2_key` instead points at the object in this
-- tenant's Cloudflare R2 bucket. Not append-only -- a mis-uploaded photo
-- may be deleted by application code.
CREATE TABLE customer_document (
    id           TEXT PRIMARY KEY,
    customer_id  TEXT NOT NULL REFERENCES customer (id),
    file_name    TEXT NOT NULL,
    mime_type    TEXT NOT NULL,
    r2_key       TEXT NOT NULL,
    created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX idx_customer_document_customer_id ON customer_document (customer_id);
