-- Control Plane: the single, shared D1 database that knows about every
-- tenant (shop). It never holds business data (customers, sales,
-- payments) -- that lives in each tenant's own isolated D1 database
-- (see cloud/tenant-template/schema). This database only answers two
-- questions for the Worker on every request: "who is this user, and
-- which tenant database do they belong to?" and "is their subscription
-- still active?"
--
-- IDs are UUIDs (TEXT) everywhere, generated by application code before
-- insert -- D1/SQLite has no built-in UUID generator.

CREATE TABLE tenant (
    id                      TEXT PRIMARY KEY,
    shop_name               TEXT NOT NULL,
    owner_name              TEXT NOT NULL,
    phone                   TEXT NOT NULL,
    email                   TEXT NOT NULL,
    d1_database_id          TEXT NOT NULL,
    -- 'trial' | 'active' | 'expired' | 'suspended'
    status                  TEXT NOT NULL DEFAULT 'trial'
                                CHECK (status IN ('trial', 'active', 'expired', 'suspended')),
    subscription_expires_at TEXT NOT NULL,
    created_at              TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE UNIQUE INDEX idx_tenant_d1_database_id ON tenant (d1_database_id);

-- One row per login (the shop owner today; room for staff accounts later
-- without a schema change). Every account belongs to exactly one tenant.
CREATE TABLE account (
    id            TEXT PRIMARY KEY,
    tenant_id     TEXT NOT NULL REFERENCES tenant (id),
    email         TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role          TEXT NOT NULL DEFAULT 'owner' CHECK (role IN ('owner', 'staff')),
    created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE UNIQUE INDEX idx_account_email ON account (email);
CREATE INDEX idx_account_tenant_id ON account (tenant_id);

-- Append-only trail of manual subscription activations/extensions, so
-- there's a record of who (which admin) extended which tenant and when --
-- needed since billing is a manual admin action, not an automated gateway.
CREATE TABLE subscription_event (
    id           TEXT PRIMARY KEY,
    tenant_id    TEXT NOT NULL REFERENCES tenant (id),
    action       TEXT NOT NULL CHECK (action IN ('activate', 'extend', 'suspend')),
    new_expires_at TEXT,
    note         TEXT,
    created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX idx_subscription_event_tenant_id ON subscription_event (tenant_id);
